version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskmanager_postgres
    restart: always
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: simopost
      POSTGRES_PASSWORD:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .   # path to your Spring Boot project
      dockerfile: Dockerfile
    container_name: taskmanager_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_db
      SPRING_DATASOURCE_USERNAME: simopost
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  frontend:
    build:
      context: ../../AngularProjects/task-manager-front   # path to your Angular project
      dockerfile: Dockerfile
    container_name: taskmanager_front
    ports:
      - "4200:80"
    depends_on:
      - app

volumes:
  postgres_data: